---
version: '3'

services:
  drupal:
    build:
      context: .
      args:
        - DRUPAL_BASE_IMAGE="geerlingguy/drupal:latest"
    volumes:
      - './:/var/www/html:rw'
    environment:
      CI: 'true'
