---
version: '3'

services:
  drupal:
    image: jeffgeerling-com:latest
    build: .
    container_name: jeffgeerling-com
    environment:
      DRUPAL_DATABASE_HOST: 'mysql'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'drupal'
      DRUPAL_DATABASE_USERNAME: 'drupal'
      DRUPAL_DATABASE_PASSWORD: 'drupal'
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: 'false'
    ports:
      - "80:80"
    # restart: on-failure

  mysql:
    image: mysql:5.7
    container_name: drupal-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    # restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
